version: '3.4'

services:
  project:
    build:
      dockerfile: dev.Dockerfile
    env_file: .env
    ports:
      - 9229:9229
    volumes:
      # - ./build:/opt/nodejs/build:rw
      - ./src:/opt/nodejs/src:ro
